OPENAI_API_KEY = "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"

FMP_API_KEY = "1Q2RGnG0j1Q5aevwSqSVykLkY6vnqIB5"